spring:
  application:
    name: book-provider
#eureka:
#  instance:
#    hostname: book-provider-1
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true # 是否注册到 eureka-server ，此处为 true , 作为一个 service provider 应当将自己注册到以达到服务化
#    fetch-registry: false # 是否从  eureka-server 下载服务列表，不消费服务可以不下载服务列表
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # 代表了一个启动示例的标识，自定义，可以显示在控制台上，
    prefer-ip-address: true # 调用服务的时候使用 IP 优先，而不是使用域名。鼠标放到应用列表的实例上，状态类中的地址信息指定为 ip。
    lease-renewal-interval-in-seconds: 10 # 表示 eureka client 发送心跳给server端的频率。这个值决定了服务注册的快慢，太快消耗资源。默认30秒。
    lease-expiration-duration-in-seconds: 30 # 表示 eureka server 至上一次收到 client 的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该 instance。默认90秒 。 上报 eureka server 如何对待改 instance
  client:
    healthcheck:
      enabled: true