spring:
  security:
    user:
      name: user
      password: 123123
eureka:
  client: # eureka client 设置
    serviceUrl:
      defaultZone: http://user:123123@eureka-server-1:34001/eureka/ # 注册中心集群地址
  environment: dev # 当前环境，可现实在UI
  datacenter: personal-computer  # 当前数据中心，可现实在UI